
import { supabase } from '@/lib/customSupabaseClient';

/**
 * Distributes Impact Credits through the MLM hierarchy.
 * @param {string} user_id - The ID of the user who performed the action (the source of value).
 * @param {number} amount - The total amount of credits generated by the action to be distributed.
 * @param {string} source - Description of the source action (e.g. 'quest_completion', 'purchase').
 */
export const distributeCreditsToUpline = async (user_id, amount, source) => {
  try {
    // 1. Obtener referrer del usuario (Upline Nivel 1)
    const { data: profile, error: profileError } = await supabase
      .from('profiles')
      .select('referrer_id')
      .eq('id', user_id)
      .single();

    if (profileError) throw profileError;
    if (!profile?.referrer_id) return; // Sin referrer, no hay distribución

    // Configuración de porcentajes MLM
    // Referrer Directo: 70% del pool de incentivo
    // Referrer Indirecto: 30% del pool de incentivo
    // Nota: 'amount' aquí representa el "Incentive Pool", no el valor total de la acción del usuario.
    // Por ejemplo, si una compra genera 100 IC de comisión MLM, 70 van al directo, 30 al indirecto.
    const directAmount = Math.floor(amount * 0.7);
    const indirectAmount = Math.floor(amount * 0.3);

    // 2. Distribuir a Referrer Directo
    const { error: directError } = await supabase
      .from('gamification_history')
      .insert({
        user_id: profile.referrer_id,
        action_id: null, // Sistema
        points_earned: directAmount,
        source: `mlm_direct_${source}`,
        notes: `MLM Reward from direct referral ${user_id.slice(0,6)}...`,
        created_at: new Date().toISOString()
      });

    if (directError) {
        console.error("Error distributing direct MLM:", directError);
        // Continue to try indirect even if direct fails? Usually fail safe.
    } else {
        // Update Balance
        await supabase.rpc('add_to_unvested_balance', { user_id_input: profile.referrer_id, amount_input: directAmount });
        await supabase.rpc('create_notification', { p_user_id: profile.referrer_id, p_title: "MLM Reward!", p_message: `You earned ${directAmount} IC from a direct referral activity.`});
    }

    // 3. Obtener referrer del referrer (Upline Nivel 2)
    const { data: referrerProfile } = await supabase
      .from('profiles')
      .select('referrer_id')
      .eq('id', profile.referrer_id)
      .single();

    if (referrerProfile?.referrer_id && indirectAmount > 0) {
      const { error: indirectError } = await supabase
        .from('gamification_history')
        .insert({
          user_id: referrerProfile.referrer_id,
          action_id: null,
          points_earned: indirectAmount,
          source: `mlm_indirect_${source}`,
          notes: `MLM Reward from indirect referral (Tier 2)`,
          created_at: new Date().toISOString()
        });

      if (!indirectError) {
          await supabase.rpc('add_to_unvested_balance', { user_id_input: referrerProfile.referrer_id, amount_input: indirectAmount });
          await supabase.rpc('create_notification', { p_user_id: referrerProfile.referrer_id, p_title: "Network Bonus!", p_message: `You earned ${indirectAmount} IC from your extended network.`});
      }
    }

  } catch (err) {
    console.error('MLM distribution error:', err);
    throw err;
  }
};
